language: php
phps:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

branches:
  only:
    - master
    - develop

before_script:
  - gem install compass
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install

script: vendor/bin/phpunit
